import time
import json
import hashlib
from dataclasses import dataclass
# In production: from cryptography.hazmat.primitives.asymmetric import ed25519

@dataclass
class SignedSensorPayload:
    """The raw payload generated by the hardware smart manifold."""
    device_pubkey: str
    timestamp_unix: int
    inlet_temp_c: float
    outlet_temp_c: float
    flow_rate_lpm: float
    signature: str  # Cryptographic signature of the data

def verify_hardware_signature(payload: SignedSensorPayload) -> bool:
    """
    [10/10 UPGRADE] Verifies the IoT device signature and prevents replay attacks.
    """
    current_time = int(time.time())
    
    # 1. Replay Attack Protection (Reject payloads older than 5 minutes)
    if abs(current_time - payload.timestamp_unix) > 300:
        print("❌ VALIDATION FAILED: Payload timestamp is stale (Replay Attack).")
        return False
        
    # 2. Cryptographic Signature Verification
    # In production, use standard Ed25519 or secp256k1 verification here.
    # payload_string = f"{payload.device_pubkey}{payload.timestamp_unix}{payload.inlet_temp_c}..."
    # return ed25519_verify(payload.device_pubkey, payload_string, payload.signature)
    
    # Mocking successful verification for architecture demonstration
    return True

def calculate_actual_btu_from_fluid(inlet_c: float, outlet_c: float, flow_lpm: float) -> float:
    """
    [10/10 UPGRADE] Node calculates the BTU itself from raw fluid dynamics.
    Q = m_dot * Cp * Delta_T
    """
    # Assuming water/glycol mix: Cp ≈ 4.18 kJ/kg.C, Density ≈ 1 kg/L
    delta_t = abs(outlet_c - inlet_c)
    mass_flow_rate_kg_s = flow_lpm / 60.0
    
    # Q in kW
    heat_transfer_kw = mass_flow_rate_kg_s * 4.18 * delta_t
    
    # Convert kW to BTU/hr (1 kW = 3412.14 BTU/hr)
    return heat_transfer_kw * 3412.14

# --- Integration into your main pipeline ---
def autonomous_thermal_validator_node(payload_json: str, params: GeothermalParams = None):
    print("Initiating Trustless IoT Thermal Validation...")
    
    data = json.loads(payload_json)
    sensor_payload = SignedSensorPayload(**data)
    
    # 1. Verify the hardware is legitimate and not a replay attack
    if not verify_hardware_signature(sensor_payload):
        return {"status": "FAIL - Invalid Hardware Signature"}
        
    # 2. Node calculates the actual thermal yield itself
    actual_btu_hr = calculate_actual_btu_from_fluid(
        sensor_payload.inlet_temp_c, 
        sensor_payload.outlet_temp_c, 
        sensor_
